### ISSUE TITLE
First Version

### ISSUE THREAD

**Issue by soyowendy** [soyowendy/simple-bank#2]
# Overview
An MVP of a simple banking system.

Simple operations that any bank should perform.

## ToDo

 - [ ] Create Bank Entity
 - [ ] Create User Entity
 - [ ] Create Account Entity
 - [ ] Create Transactions Entity

 - [ ] Create Login
 - [ ] Create Menu

 - [ ] Show account transaction history
 - [ ] Make Withdraw
 - [ ] Make Deposit
 - [ ] Make Transfer
